// Auto-generated by Sireum Presentasi
import javafx.application.Application;
import javafx.application.Platform;
import javafx.geometry.Rectangle2D;
import javafx.scene.Scene;
import javafx.scene.image.ImageView;
import javafx.scene.layout.StackPane;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javafx.stage.Screen;
import javafx.stage.Stage;
import javafx.util.Duration;

import java.net.URL;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;

public class Presentasi extends Application {

    public final static long TIMELINE_GRANULARITY = 1;
    public final static long VSEEK_DELAY = 250;
    public final static double TEXT_VOLUME = 1.0;

    public final static HashMap<String, javafx.scene.media.Media> mediaMap = new HashMap<String, javafx.scene.media.Media>();

    public static javafx.scene.media.Media getJfxMedia(String uri) {
        javafx.scene.media.Media r = mediaMap.get(uri);
        if (r == null) {
           r =  new javafx.scene.media.Media(uri);
           mediaMap.put(uri, r);
        }
        return r;
    }

    public interface Media {
        String getUri();
        boolean isReady();
        boolean hasError();
        long getDurationMillis();
        long getTimeline();
    }

    public final static class Image implements Media {
        public final String uri;
        public final ImageView imageView;
        private final long timeline;

        public Image(final String path, final long timeline) {
            this.uri = getResourceUri(path);
            this.timeline = timeline;
            this.imageView = new ImageView(new javafx.scene.image.Image(uri));
        }

        public String getUri() { return this.uri; }

        public boolean isReady() {
            return true;
        }

        public boolean hasError() {
            return false;
        }

        public long getDurationMillis() {
            return 0L;
        }

        public long getTimeline() {
            return this.timeline;
        }
    }

    public final static class Sound implements Media {
        public final String uri;
        private final long timeline;
        public MediaPlayer mediaPlayer;
        private boolean ready = false;
        private boolean error = false;
        private long duration = 0L;

        public Sound(final String path, final long timeline) {
            this.uri = getResourceUri(path);
            this.timeline = timeline;
            try {
              this.mediaPlayer = new MediaPlayer(getJfxMedia(this.uri));
              this.mediaPlayer.setOnReady(() -> {
                  this.ready = true;
                  this.duration = (long) Math.ceil(mediaPlayer.getTotalDuration().toMillis());
              });
              this.mediaPlayer.setOnError(() -> this.error = true);
            } catch (Throwable e) {
              e.printStackTrace();
              System.err.println("Could not load: " + path);
              System.err.flush();
              System.exit(-1);
            }
        }

        public String getUri() { return this.uri; }

        public boolean isReady() {
            return this.ready;
        }

        public boolean hasError() {
            return this.error;
        }

        public long getDurationMillis() {
            return this.duration;
        }

        public long getTimeline() {
            return this.timeline;
        }
    }

    public final static class Video implements Media {
        public final String uri;
        private final long timeline;
        public MediaView mediaView;
        public final boolean muted;
        public final double rate;
        public final double startMillis;
        public final double endMillis;
        private boolean ready;
        private boolean error;
        private long duration;

        public Video(final String path, final long timeline, final boolean muted, final double rate, final double startMs, final double endMs) {
            this.uri = getResourceUri(path);
            this.timeline = timeline;
            this.rate = rate;
            this.startMillis = startMs;
            this.endMillis = endMs;
            this.muted = muted;
            try {
              final MediaPlayer mediaPlayer = new MediaPlayer(getJfxMedia(this.uri));
              mediaPlayer.setOnReady(() -> {
                  this.ready = true;
                  if (endMs > 0.0) {
                      this.duration = (long) Math.ceil(endMs - startMs);
                  } else {
                      this.duration = (long) Math.ceil(mediaPlayer.getTotalDuration().toMillis());
                  }
              });
              mediaPlayer.setOnError(() -> this.error = true);
              this.mediaView = new MediaView(mediaPlayer);
            } catch (Throwable e) {
              e.printStackTrace();
              System.err.println("Could not load: " + path);
              System.err.flush();
              System.exit(-1);
            }
        }

        public String getUri() { return this.uri; }

        public boolean isReady() {
            return this.ready;
        }

        public boolean hasError() { return this.error; }

        public long getDurationMillis() {
            return this.duration;
        }

        public long getTimeline() {
            return this.timeline;
        }
    }

    private final LinkedList<Media> medias = new LinkedList<>();
    private Stage stage = null;
    private long startTime = 0;
    private int slideNo = 0;
    private boolean fullScreen = true;
    private double width = -1;
    private double height = -1;

    public static String getResourceUri(final String path) {
        try {
            final URL url = Presentasi.class.getResource(path);
            if (url != null) {
                return url.toURI().toASCIIString();
            }
            throw new RuntimeException("Could not load " + path);
        } catch (final Throwable t){
            t.printStackTrace();
        }
        Platform.exit();
        return null;
    }

    @Override
    public void init() {
        final List<String> args = getParameters().getRaw();
        if (args.size() > 0) {
            for (String arg : getParameters().getRaw()) {
                try {
                    int i = arg.indexOf('x');
                    if (i >= 0) {
                        width = Integer.parseInt(arg.substring(0, i));
                        height = Integer.parseInt(arg.substring(i + 1));
                        fullScreen = false;
                    } else if (arg.charAt(0) == '#') {
                        slideNo = Integer.parseInt(arg.substring(1));
                        startTime = 0;
                    } else {
                        startTime = Long.parseLong(arg);
                        slideNo = 0;
                    }
                } catch (Throwable t) {
                    System.err.println("Invalid argument " + arg);
                    System.err.flush();
                    Platform.exit();
                }
            }
        }

        final long t_0 = 0L; // 0 (00:00:00:000)
        medias.add(new Image("/image/01-intro.png", t_0)); // #0
        final long t_1 = t_0 + 1800L; // 1800 (00:00:01:800)
        medias.add(new Sound("/audio/azure/443ED6-Hello_.mp3", t_1));
        final long t_2 = t_1 + 1690L; // 3490 (00:00:03:490)
        medias.add(new Sound("/audio/azure/60B52E-We_d_like_to_sh.mp3", t_2));
        final long t_3 = t_2 + 7018L; // 10508 (00:00:10:508)
        medias.add(new Sound("/audio/azure/70E3B6-This_work_is_fu.mp3", t_3));
        final long t_4 = t_3 + 7232L; // 17740 (00:00:17:740)
        medias.add(new Image("/image/02-vision-01-sel4-1.png", t_4)); // #1
        final long t_5 = t_4;
        medias.add(new Sound("/audio/azure/934464-This_conference.mp3", t_5));
        final long t_6 = t_5 + 10450L; // 28190 (00:00:28:190)
        medias.add(new Sound("/audio/azure/D0F8B9-In_this_talk__w.mp3", t_6));
        final long t_7 = t_6 + 6800L; // 34990 (00:00:34:990)
        medias.add(new Image("/image/02-vision-02-sel4-2.png", t_7)); // #2
        final long t_8 = t_7;
        medias.add(new Sound("/audio/azure/9DFD5B-In_particular__.mp3", t_8));
        final long t_9 = t_8 + 11818L; // 46808 (00:00:46:808)
        medias.add(new Sound("/audio/azure/41B079-S_E_L__4_is_wri.mp3", t_9));
        final long t_10 = t_9 + 6874L; // 53682 (00:00:53:682)
        medias.add(new Sound("/audio/azure/AA1B41-What_types_of_f.mp3", t_10));
        final long t_11 = t_10 + 3346L; // 57028 (00:00:57:028)
        medias.add(new Sound("/audio/azure/FBFE77-S_E_L__4_verifi.mp3", t_11));
        final long t_12 = t_11 + 12658L; // 69686 (00:01:09:686)
        medias.add(new Sound("/audio/azure/60A339-Moreover__devel.mp3", t_12));
        final long t_13 = t_12 + 9538L; // 79224 (00:01:19:224)
        medias.add(new Sound("/audio/azure/97A67F-And_how_should_.mp3", t_13));
        final long t_14 = t_13 + 7304L; // 86528 (00:01:26:528)
        medias.add(new Image("/image/02-vision-03-hamr-1.png", t_14)); // #3
        final long t_15 = t_14;
        medias.add(new Sound("/audio/azure/8FF368-In_a_tutorial_s.mp3", t_15));
        final long t_16 = t_15 + 7426L; // 93954 (00:01:33:954)
        medias.add(new Sound("/audio/azure/9C817C-In_particular__.mp3", t_16));
        final long t_17 = t_16 + 18152L; // 112106 (00:01:52:106)
        medias.add(new Image("/image/02-vision-04-hamr-2.png", t_17)); // #4
        final long t_18 = t_17;
        medias.add(new Sound("/audio/azure/1063BC-To_summarize__H.mp3", t_18));
        final long t_19 = t_18 + 7756L; // 119862 (00:01:59:862)
        medias.add(new Image("/image/02-vision-05-hamr-3.png", t_19)); // #5
        final long t_20 = t_19 + 500L; // 120362 (00:02:00:362)
        medias.add(new Sound("/audio/azure/1727DA-It_also_generat.mp3", t_20));
        final long t_21 = t_20 + 10300L; // 130662 (00:02:10:662)
        medias.add(new Image("/image/02-vision-06-hamr-4.png", t_21)); // #6
        final long t_22 = t_21 + 500L; // 131162 (00:02:11:162)
        medias.add(new Sound("/audio/azure/78F031-and_then_automa.mp3", t_22));
        final long t_23 = t_22 + 5768L; // 136930 (00:02:16:930)
        medias.add(new Image("/image/02-vision-07-hamr-aspects-1.png", t_23)); // #7
        final long t_24 = t_23;
        medias.add(new Sound("/audio/azure/15AF97-To_a_large_exte.mp3", t_24));
        final long t_25 = t_24 + 7180L; // 144110 (00:02:24:110)
        medias.add(new Image("/image/02-vision-08-hamr-aspects-2.png", t_25)); // #8
        final long t_26 = t_25 + 500L; // 144610 (00:02:24:610)
        medias.add(new Sound("/audio/azure/5662CB-Firstly__it_con.mp3", t_26));
        final long t_27 = t_26 + 7132L; // 151742 (00:02:31:742)
        medias.add(new Image("/image/02-vision-09-hamr-aspects-3.png", t_27)); // #9
        final long t_28 = t_27 + 500L; // 152242 (00:02:32:242)
        medias.add(new Sound("/audio/azure/74E5D2-System_builds_a.mp3", t_28));
        final long t_29 = t_28 + 8836L; // 161078 (00:02:41:078)
        medias.add(new Image("/image/02-vision-10-hamr-aspects-4.png", t_29)); // #10
        final long t_30 = t_29 + 500L; // 161578 (00:02:41:578)
        medias.add(new Sound("/audio/azure/786C12-Safety_and_secu.mp3", t_30));
        final long t_31 = t_30 + 9604L; // 171182 (00:02:51:182)
        medias.add(new Image("/image/02-vision-11-hamr-aspects-5.png", t_31)); // #11
        final long t_32 = t_31 + 500L; // 171682 (00:02:51:682)
        medias.add(new Sound("/audio/azure/37E604-System_updates_.mp3", t_32));
        final long t_33 = t_32 + 11096L; // 182778 (00:03:02:778)
        medias.add(new Image("/image/02-vision-12-pl-1.png", t_33)); // #12
        final long t_34 = t_33;
        medias.add(new Sound("/audio/azure/E5D463-Given_that_Hamm.mp3", t_34));
        final long t_35 = t_34 + 11168L; // 193946 (00:03:13:946)
        medias.add(new Image("/image/02-vision-13-pl-2.png", t_35)); // #13
        final long t_36 = t_35;
        medias.add(new Sound("/audio/azure/490FEE-On_Monday__we_i.mp3", t_36));
        final long t_37 = t_36 + 8554L; // 202500 (00:03:22:500)
        medias.add(new Sound("/audio/azure/DC795B-However__our_vi.mp3", t_37));
        final long t_38 = t_37 + 7786L; // 210286 (00:03:30:286)
        medias.add(new Sound("/audio/azure/66CFCD-In_particular__.mp3", t_38));
        final long t_39 = t_38 + 8266L; // 218552 (00:03:38:552)
        medias.add(new Sound("/audio/azure/124837-It_is_amenable_.mp3", t_39));
        final long t_40 = t_39 + 9394L; // 227946 (00:03:47:946)
        medias.add(new Sound("/audio/azure/687A0B-It_integrates_e.mp3", t_40));
        final long t_41 = t_40 + 9176L; // 237122 (00:03:57:122)
        medias.add(new Image("/image/02-vision-14-tool.png", t_41)); // #14
        final long t_42 = t_41;
        medias.add(new Sound("/audio/azure/792B59-So_today_we_are.mp3", t_42));
        final long t_43 = t_42 + 9562L; // 246684 (00:04:06:684)
        medias.add(new Sound("/audio/azure/B7B44F-These_tools_are.mp3", t_43));
        final long t_44 = t_43 + 6632L; // 253316 (00:04:13:316)
        medias.add(new Image("/image/03-slang-1.png", t_44)); // #15
        final long t_45 = t_44;
        medias.add(new Sound("/audio/azure/C06897-Slang_is_a_safe.mp3", t_45));
        final long t_46 = t_45 + 5266L; // 258582 (00:04:18:582)
        medias.add(new Sound("/audio/azure/1D557F-Due_to_Scala_s_.mp3", t_46));
        final long t_47 = t_46 + 10138L; // 268720 (00:04:28:720)
        medias.add(new Sound("/audio/azure/6515FC-Moreover__Slang.mp3", t_47));
        final long t_48 = t_47 + 12538L; // 281258 (00:04:41:258)
        medias.add(new Sound("/audio/azure/2192D4-In_addition__Sl.mp3", t_48));
        final long t_49 = t_48 + 9538L; // 290796 (00:04:50:796)
        medias.add(new Sound("/audio/azure/67E99E-Slang_offers_a_.mp3", t_49));
        final long t_50 = t_49 + 8626L; // 299422 (00:04:59:422)
        medias.add(new Sound("/audio/azure/0DAB38-Another_reason_.mp3", t_50));
        final long t_51 = t_50 + 13832L; // 313254 (00:05:13:254)
        medias.add(new Image("/image/03-slang-2.png", t_51)); // #16
        final long t_52 = t_51;
        medias.add(new Sound("/audio/azure/AB5FA9-Due_to_its_care.mp3", t_52));
        final long t_53 = t_52 + 5746L; // 319000 (00:05:19:000)
        medias.add(new Sound("/audio/azure/060845-The_Slang_embed.mp3", t_53));
        final long t_54 = t_53 + 8194L; // 327194 (00:05:27:194)
        medias.add(new Sound("/audio/azure/9AC2F1-For_achieving_a.mp3", t_54));
        final long t_55 = t_54 + 7450L; // 334644 (00:05:34:644)
        medias.add(new Sound("/audio/azure/B2E298-The_generated_C.mp3", t_55));
        final long t_56 = t_55 + 8480L; // 343124 (00:05:43:124)
        medias.add(new Image("/image/03-slang-3.png", t_56)); // #17
        final long t_57 = t_56;
        medias.add(new Sound("/audio/azure/9536AF-To_support_form.mp3", t_57));
        final long t_58 = t_57 + 9776L; // 352900 (00:05:52:900)
        medias.add(new Image("/image/03-slang-4.png", t_58)); // #18
        final long t_59 = t_58;
        medias.add(new Sound("/audio/azure/AE94D2-To_support_auto.mp3", t_59));
        final long t_60 = t_59 + 9634L; // 362534 (00:06:02:534)
        medias.add(new Sound("/audio/azure/AC6EDF-Simplification_.mp3", t_60));
        final long t_61 = t_60 + 7018L; // 369552 (00:06:09:552)
        medias.add(new Sound("/audio/azure/F825A7-For_example__we.mp3", t_61));
        final long t_62 = t_61 + 11242L; // 380794 (00:06:20:794)
        medias.add(new Sound("/audio/azure/DC777C-Thus__aliasing_.mp3", t_62));
        final long t_63 = t_62 + 6200L; // 386994 (00:06:26:994)
        medias.add(new Image("/image/04-logika-1.png", t_63)); // #19
        final long t_64 = t_63;
        medias.add(new Sound("/audio/azure/58A468-To_support_deve.mp3", t_64));
        final long t_65 = t_64 + 10016L; // 397010 (00:06:37:010)
        medias.add(new Image("/image/04-logika-2.png", t_65)); // #20
        final long t_66 = t_65;
        medias.add(new Sound("/audio/azure/6B130A-Verification_is.mp3", t_66));
        final long t_67 = t_66 + 10136L; // 407146 (00:06:47:146)
        medias.add(new Image("/image/04-logika-3.png", t_67)); // #21
        final long t_68 = t_67;
        medias.add(new Sound("/audio/azure/96ADE2-This_continuous.mp3", t_68));
        final long t_69 = t_68 + 13256L; // 420402 (00:07:00:402)
        medias.add(new Image("/image/04-logika-4.png", t_69)); // #22
        final long t_70 = t_69;
        medias.add(new Sound("/audio/azure/FB4ECC-This_incrementa.mp3", t_70));
        final long t_71 = t_70 + 3634L; // 424036 (00:07:04:036)
        medias.add(new Sound("/audio/azure/5DDFCF-When_updates_ar.mp3", t_71));
        final long t_72 = t_71 + 5914L; // 429950 (00:07:09:950)
        medias.add(new Sound("/audio/azure/AC45F9-Scalability_is_.mp3", t_72));
        final long t_73 = t_72 + 8146L; // 438096 (00:07:18:096)
        medias.add(new Sound("/audio/azure/9FFC7F-This_provides_a.mp3", t_73));
        final long t_74 = t_73 + 8624L; // 446720 (00:07:26:720)
        medias.add(new Image("/image/04-logika-5.png", t_74)); // #23
        final long t_75 = t_74;
        medias.add(new Sound("/audio/azure/FC6BD4-Finally__since_.mp3", t_75));
        final long t_76 = t_75 + 17624L; // 464344 (00:07:44:344)
        medias.add(new Image("/image/05-logika-themes-1.png", t_76)); // #24
        final long t_77 = t_76;
        medias.add(new Sound("/audio/azure/967751-We_ll_now_provi.mp3", t_77));
        final long t_78 = t_77 + 5216L; // 469560 (00:07:49:560)
        medias.add(new Image("/image/05-logika-themes-2.png", t_78)); // #25
        final long t_79 = t_78;
        medias.add(new Sound("/audio/azure/DC3855-Let_s_start_wit.mp3", t_79));
        final long t_80 = t_79 + 11432L; // 480992 (00:08:00:992)
        medias.add(new Video("/video/06-demo-logika-intro.mp4", t_80, true, 1.0, 0.0, 0.0));  // #26
        final long t_81 = t_80;
        medias.add(new Sound("/audio/azure/CEC6E2-We_ll_see_how_t.mp3", t_81));
        final long t_82 = t_81 + 8290L; // 489282 (00:08:09:282)
        medias.add(new Sound("/audio/azure/D74FB0-IntelliJay_prov.mp3", t_82));
        final long t_83 = t_82 + 4272L; // 493554 (00:08:13:554)
        medias.add(new Video("/video/06-demo-logika.mp4", t_83, true, 1.0, 15066.7, 24000.0));  // #27
        final long t_84 = t_83 + 3800L; // 497354 (00:08:17:354)
        medias.add(new Sound("/audio/azure/D50F93-Slang_analysis_.mp3", t_84));
        final long t_85 = t_84 + 6370L; // 503724 (00:08:23:724)
        medias.add(new Sound("/audio/azure/FF625E-Here__we_have_s.mp3", t_85));
        final long t_86 = t_85 + 7138L; // 510862 (00:08:30:862)
        medias.add(new Sound("/audio/azure/467B39-The_example_dec.mp3", t_86));
        final long t_87 = t_86 + 5746L; // 516608 (00:08:36:608)
        medias.add(new Sound("/audio/azure/C51C8C-A_mission_typic.mp3", t_87));
        final long t_88 = t_87 + 7186L; // 523794 (00:08:43:794)
        medias.add(new Sound("/audio/azure/2D6256-As_Logeeka_work.mp3", t_88));
        final long t_89 = t_88 + 6440L; // 530234 (00:08:50:234)
        medias.add(new Video("/video/06-demo-logika.mp4", t_89, true, 1.0, 26500.0, 30000.0));  // #28
        final long t_90 = t_89;
        medias.add(new Sound("/audio/azure/7F8354-It_decorates_ea.mp3", t_90));
        final long t_91 = t_90 + 2872L; // 533106 (00:08:53:106)
        medias.add(new Video("/video/06-demo-logika.mp4", t_91, true, 1.5, 30000.0, 47000.0));  // #29
        final long t_92 = t_91 + 1400L; // 534506 (00:08:54:506)
        medias.add(new Sound("/audio/azure/A25E92-which_aids_prog.mp3", t_92));
        final long t_93 = t_92 + 4930L; // 539436 (00:08:59:436)
        medias.add(new Sound("/audio/azure/EE13BE-The_state_claim.mp3", t_93));
        final long t_94 = t_93 + 4296L; // 543732 (00:09:03:732)
        medias.add(new Sound("/audio/azure/69EC1F-and_as_you_can_.mp3", t_94));
        final long t_95 = t_94 + 7282L; // 551014 (00:09:11:014)
        medias.add(new Sound("/audio/azure/3E8311-This_is_the_dir.mp3", t_95));
        final long t_96 = t_95 + 9296L; // 560310 (00:09:20:310)
        medias.add(new Video("/video/06-demo-logika.mp4", t_96, true, 1.0, 54500.0, 57500.0));  // #30
        final long t_97 = t_96;
        medias.add(new Sound("/audio/azure/7EDA2F-Logeeka_also_de.mp3", t_97));
        final long t_98 = t_97 + 8314L; // 568624 (00:09:28:624)
        medias.add(new Sound("/audio/azure/F472E4-Each_query_is_a.mp3", t_98));
        final long t_99 = t_98 + 7688L; // 576312 (00:09:36:312)
        medias.add(new Video("/video/06-demo-logika.mp4", t_99, true, 1.0, 63000.0, 69000.0));  // #31
        final long t_100 = t_99;
        medias.add(new Sound("/audio/azure/AB613D-Each_sequence_o.mp3", t_100));
        final long t_101 = t_100 + 8168L; // 584480 (00:09:44:480)
        medias.add(new Video("/video/06-demo-logika.mp4", t_101, true, 1.0, 69000.0, 80000.0));  // #32
        final long t_102 = t_101;
        medias.add(new Sound("/audio/azure/4C7464-Suppose_that_we.mp3", t_102));
        final long t_103 = t_102 + 9850L; // 594330 (00:09:54:330)
        medias.add(new Sound("/audio/azure/356E5B-We_believe_such.mp3", t_103));
        final long t_104 = t_103 + 7136L; // 601466 (00:10:01:466)
        medias.add(new Video("/video/06-demo-logika.mp4", t_104, true, 1.0, 92000.0, 102000.0));  // #33
        final long t_105 = t_104;
        medias.add(new Sound("/audio/azure/DC637F-As_issues_are_f.mp3", t_105));
        final long t_106 = t_105 + 6946L; // 608412 (00:10:08:412)
        medias.add(new Sound("/audio/azure/31DE81-We_like_this_li.mp3", t_106));
        final long t_107 = t_106 + 9992L; // 618404 (00:10:18:404)
        medias.add(new Video("/video/06-demo-logika.mp4", t_107, true, 1.0, 103750.0, 118250.0));  // #34
        final long t_108 = t_107;
        medias.add(new Sound("/audio/azure/8C5CAD-Let_us_now_star.mp3", t_108));
        final long t_109 = t_108 + 6514L; // 624918 (00:10:24:918)
        medias.add(new Sound("/audio/azure/06A296-For_example__we.mp3", t_109));
        final long t_110 = t_109 + 9226L; // 634144 (00:10:34:144)
        medias.add(new Sound("/audio/azure/29B08E-Obviously__such.mp3", t_110));
        final long t_111 = t_110 + 8528L; // 642672 (00:10:42:672)
        medias.add(new Video("/video/06-demo-logika.mp4", t_111, true, 1.0, 118250.0, 135000.0));  // #35
        final long t_112 = t_111;
        medias.add(new Sound("/audio/azure/6AC9B9-Suppose_that_we.mp3", t_112));
        final long t_113 = t_112 + 4234L; // 646906 (00:10:46:906)
        medias.add(new Sound("/audio/azure/C5E584-This_is_where_S.mp3", t_113));
        final long t_114 = t_113 + 7810L; // 654716 (00:10:54:716)
        medias.add(new Sound("/audio/azure/71D875-Thus__the_asser.mp3", t_114));
        final long t_115 = t_114 + 3512L; // 658228 (00:10:58:228)
        medias.add(new Video("/video/06-demo-logika.mp4", t_115, true, 1.0, 142500.0, 153500.0));  // #36
        final long t_116 = t_115;
        medias.add(new Sound("/audio/azure/DA64D1-We_can_confirm_.mp3", t_116));
        final long t_117 = t_116 + 8866L; // 667094 (00:11:07:094)
        medias.add(new Sound("/audio/azure/7EE8FB-Once_it_finishe.mp3", t_117));
        final long t_118 = t_117 + 7954L; // 675048 (00:11:15:048)
        medias.add(new Sound("/audio/azure/CFC37F-This_illustrate.mp3", t_118));
        final long t_119 = t_118 + 6752L; // 681800 (00:11:21:800)
        medias.add(new Video("/video/06-demo-logika.mp4", t_119, true, 1.0, 161500.0, 173750.0));  // #37
        final long t_120 = t_119;
        medias.add(new Sound("/audio/azure/09C8A1-Due_to_the_deep.mp3", t_120));
        final long t_121 = t_120 + 6826L; // 688626 (00:11:28:626)
        medias.add(new Sound("/audio/azure/0D906B-We_can_ask_Loge.mp3", t_121));
        final long t_122 = t_121 + 4234L; // 692860 (00:11:32:860)
        medias.add(new Sound("/audio/azure/417114-One_might_think.mp3", t_122));
        final long t_123 = t_122 + 10666L; // 703526 (00:11:43:526)
        medias.add(new Sound("/audio/azure/C34BB8-On_cases_where_.mp3", t_123));
        final long t_124 = t_123 + 9800L; // 713326 (00:11:53:326)
        medias.add(new Video("/video/06-demo-logika.mp4", t_124, true, 2.0, 173750.0, 179500.0));  // #38
        final long t_125 = t_124;
        medias.add(new Sound("/audio/azure/96725B-Let_us_now_look.mp3", t_125));
        final long t_126 = t_125 + 4136L; // 717462 (00:11:57:462)
        medias.add(new Video("/video/06-demo-logika.mp4", t_126, true, 1.0, 181000.0, 197500.0));  // #39
        final long t_127 = t_126;
        medias.add(new Sound("/audio/azure/9F0D2C-I_am_going_to_c.mp3", t_127));
        final long t_128 = t_127 + 5154L; // 722616 (00:12:02:616)
        medias.add(new Sound("/audio/azure/A63266-You_can_observe.mp3", t_128));
        final long t_129 = t_128 + 4546L; // 727162 (00:12:07:162)
        medias.add(new Sound("/audio/azure/C15B4F-Both_inZone_and.mp3", t_129));
        final long t_130 = t_129 + 6082L; // 733244 (00:12:13:244)
        medias.add(new Sound("/audio/azure/B7C448-Such_methods_ca.mp3", t_130));
        final long t_131 = t_130 + 8794L; // 742038 (00:12:22:038)
        medias.add(new Sound("/audio/azure/31B342-Move_waypoint_X.mp3", t_131));
        final long t_132 = t_131 + 7282L; // 749320 (00:12:29:320)
        medias.add(new Sound("/audio/azure/D0FF0F-As_can_be_obser.mp3", t_132));
        final long t_133 = t_132 + 16426L; // 765746 (00:12:45:746)
        medias.add(new Sound("/audio/azure/162ABB-In_the_future__.mp3", t_133));
        final long t_134 = t_133 + 10016L; // 775762 (00:12:55:762)
        medias.add(new Image("/image/07-education.png", t_134)); // #40
        final long t_135 = t_134;
        medias.add(new Sound("/audio/azure/4B8851-Regarding_democ.mp3", t_135));
        final long t_136 = t_135 + 11560L; // 787322 (00:13:07:322)
        medias.add(new Video("/video/08-education-web.mp4", t_136, true, 1.0, 0.0, 0.0));  // #41
        final long t_137 = t_136 + 2800L; // 790122 (00:13:10:122)
        medias.add(new Sound("/audio/azure/A89B03-It_has_proven_v.mp3", t_137));
        final long t_138 = t_137 + 8818L; // 798940 (00:13:18:940)
        medias.add(new Sound("/audio/azure/7D8BE4-Moreover__Logee.mp3", t_138));
        final long t_139 = t_138 + 8698L; // 807638 (00:13:27:638)
        medias.add(new Sound("/audio/azure/5C2EEA-The_accompanyin.mp3", t_139));
        final long t_140 = t_139 + 4282L; // 811920 (00:13:31:920)
        medias.add(new Sound("/audio/azure/0448FB-Here_you_can_ob.mp3", t_140));
        final long t_141 = t_140 + 9106L; // 821026 (00:13:41:026)
        medias.add(new Sound("/audio/azure/A36DC5-This_teaching_e.mp3", t_141));
        final long t_142 = t_141 + 11672L; // 832698 (00:13:52:698)
        medias.add(new Image("/image/09-logika-themes-incremental.png", t_142)); // #42
        final long t_143 = t_142;
        medias.add(new Sound("/audio/azure/FEB143-Now_let_s_consi.mp3", t_143));
        final long t_144 = t_143 + 7520L; // 840218 (00:14:00:218)
        medias.add(new Image("/image/10-codebase-1.png", t_144)); // #43
        final long t_145 = t_144;
        medias.add(new Sound("/audio/azure/3D632D-Up_to_this_poin.mp3", t_145));
        final long t_146 = t_145 + 5746L; // 845964 (00:14:05:964)
        medias.add(new Sound("/audio/azure/511776-So_you_may_be_w.mp3", t_146));
        final long t_147 = t_146 + 4138L; // 850102 (00:14:10:102)
        medias.add(new Sound("/audio/azure/898A2C-The_answer_is_Y.mp3", t_147));
        final long t_148 = t_147 + 2912L; // 853014 (00:14:13:014)
        medias.add(new Image("/image/10-codebase-2.png", t_148)); // #44
        final long t_149 = t_148;
        medias.add(new Sound("/audio/azure/768D83-In_addition_to_.mp3", t_149));
        final long t_150 = t_149 + 15154L; // 868168 (00:14:28:168)
        medias.add(new Sound("/audio/azure/6E7D8F-The_code_base_i.mp3", t_150));
        final long t_151 = t_150 + 10546L; // 878714 (00:14:38:714)
        medias.add(new Sound("/audio/azure/92AF1B-So_not_only_doe.mp3", t_151));
        final long t_152 = t_151 + 3496L; // 882210 (00:14:42:210)
        medias.add(new Image("/image/10-codebase-3.png", t_152)); // #45
        final long t_153 = t_152 + 1300L; // 883510 (00:14:43:510)
        medias.add(new Sound("/audio/azure/524394-it_means_that_w.mp3", t_153));
        final long t_154 = t_153 + 11312L; // 894822 (00:14:54:822)
        medias.add(new Image("/image/10-codebase-4.png", t_154)); // #46
        final long t_155 = t_154;
        medias.add(new Sound("/audio/azure/CCEAD1-This_provides_a.mp3", t_155));
        final long t_156 = t_155 + 8554L; // 903376 (00:15:03:376)
        medias.add(new Sound("/audio/azure/390247-We_re_currently.mp3", t_156));
        final long t_157 = t_156 + 6536L; // 909912 (00:15:09:912)
        medias.add(new Image("/image/10-codebase-5.png", t_157)); // #47
        final long t_158 = t_157;
        medias.add(new Sound("/audio/azure/26427A-We_re_now_going.mp3", t_158));
        final long t_159 = t_158 + 9850L; // 919762 (00:15:19:762)
        medias.add(new Sound("/audio/azure/F787C0-This_is_possibl.mp3", t_159));
        final long t_160 = t_159 + 6224L; // 925986 (00:15:25:986)
        medias.add(new Video("/video/06-demo-logika.mp4", t_160, true, 3.0, 366000.0, 370000.0));  // #48
        final long t_161 = t_160;
        medias.add(new Sound("/audio/azure/86C2D8-Let_s_look_at_t.mp3", t_161));
        final long t_162 = t_161 + 3562L; // 929548 (00:15:29:548)
        medias.add(new Sound("/audio/azure/13A903-Option_is_part_.mp3", t_162));
        final long t_163 = t_162 + 5312L; // 934860 (00:15:34:860)
        medias.add(new Video("/video/06-demo-logika.mp4", t_163, true, 1.0, 380000.0, 380500.0));  // #49
        final long t_164 = t_163;
        medias.add(new Sound("/audio/azure/C2E070-Here_you_can_se.mp3", t_164));
        final long t_165 = t_164 + 5458L; // 940318 (00:15:40:318)
        medias.add(new Sound("/audio/azure/329DBE-For_this_exampl.mp3", t_165));
        final long t_166 = t_165 + 4304L; // 944622 (00:15:44:622)
        medias.add(new Video("/video/06-demo-logika.mp4", t_166, true, 1.0, 380500.0, 385000.0));  // #50
        final long t_167 = t_166 + 1800L; // 946422 (00:15:46:422)
        medias.add(new Sound("/audio/azure/0FC47E-The_main_point_.mp3", t_167));
        final long t_168 = t_167 + 6730L; // 953152 (00:15:53:152)
        medias.add(new Sound("/audio/azure/12CF2B-Then__the_Logee.mp3", t_168));
        final long t_169 = t_168 + 10666L; // 963818 (00:16:03:818)
        medias.add(new Sound("/audio/azure/1B3248-You_just_saw_a_.mp3", t_169));
        final long t_170 = t_169 + 6464L; // 970282 (00:16:10:282)
        medias.add(new Video("/video/06-demo-logika.mp4", t_170, true, 1.0, 386250.0, 390000.0));  // #51
        final long t_171 = t_170 + 1800L; // 972082 (00:16:12:082)
        medias.add(new Sound("/audio/azure/08E4BC-Then__when_we_c.mp3", t_171));
        final long t_172 = t_171 + 7400L; // 979482 (00:16:19:482)
        medias.add(new Image("/image/11-codebase-graph.png", t_172)); // #52
        final long t_173 = t_172 + 1500L; // 980982 (00:16:20:982)
        medias.add(new Sound("/audio/azure/747F7D-Logeeka_increme.mp3", t_173));
        final long t_174 = t_173 + 8218L; // 989200 (00:16:29:200)
        medias.add(new Sound("/audio/azure/CFDE24-Just_like_an_in.mp3", t_174));
        final long t_175 = t_174 + 15370L; // 1004570 (00:16:44:570)
        medias.add(new Sound("/audio/azure/51690A-Using_this_info.mp3", t_175));
        final long t_176 = t_175 + 12080L; // 1016650 (00:16:56:650)
        medias.add(new Video("/video/12-codebase-incremental.mp4", t_176, true, 1.0, 0.0, 1700.0));  // #53
        final long t_177 = t_176;
        medias.add(new Sound("/audio/azure/7E565A-Let_me_describe.mp3", t_177));
        final long t_178 = t_177 + 2501L; // 1019151 (00:16:59:151)
        medias.add(new Video("/video/12-codebase-incremental.mp4", t_178, true, 1.0, 1700.0, 2000.0));  // #54
        final long t_179 = t_178 + 750L; // 1019901 (00:16:59:901)
        medias.add(new Sound("/audio/azure/1B83D4-When_a_particul.mp3", t_179));
        final long t_180 = t_179 + 3446L; // 1023347 (00:17:03:347)
        medias.add(new Video("/video/12-codebase-incremental.mp4", t_180, true, 1.0, 2000.0, 5000.0));  // #55
        final long t_181 = t_180 + -350L; // 1022997 (00:17:02:997)
        medias.add(new Sound("/audio/azure/A65B2C-Logeeka_starts_.mp3", t_181));
        final long t_182 = t_181 + 3284L; // 1026281 (00:17:06:281)
        medias.add(new Image("/image/13-incremental-1.png", t_182)); // #56
        final long t_183 = t_182 + 1900L; // 1028181 (00:17:08:181)
        medias.add(new Sound("/audio/azure/1EDF2E-until_it_finds_.mp3", t_183));
        final long t_184 = t_183 + 4376L; // 1032557 (00:17:12:557)
        medias.add(new Image("/image/13-incremental-2.png", t_184)); // #57
        final long t_185 = t_184;
        medias.add(new Sound("/audio/azure/BA7EB4-Along_the_way__.mp3", t_185));
        final long t_186 = t_185 + 4930L; // 1037487 (00:17:17:487)
        medias.add(new Sound("/audio/azure/9E0CBC-That_is__Logeek.mp3", t_186));
        final long t_187 = t_186 + 11432L; // 1048919 (00:17:28:919)
        medias.add(new Image("/image/13-incremental-3.png", t_187)); // #58
        final long t_188 = t_187;
        medias.add(new Sound("/audio/azure/90EA23-Only_the_Option.mp3", t_188));
        final long t_189 = t_188 + 4714L; // 1053633 (00:17:33:633)
        medias.add(new Sound("/audio/azure/769B25-In_the_context_.mp3", t_189));
        final long t_190 = t_189 + 9536L; // 1063169 (00:17:43:169)
        medias.add(new Image("/image/13-incremental-4.png", t_190)); // #59
        final long t_191 = t_190;
        medias.add(new Sound("/audio/azure/CC4088-Furthermore__Lo.mp3", t_191));
        final long t_192 = t_191 + 7042L; // 1070211 (00:17:50:211)
        medias.add(new Sound("/audio/azure/3942DA-For_example__mo.mp3", t_192));
        final long t_193 = t_192 + 6082L; // 1076293 (00:17:56:293)
        medias.add(new Sound("/audio/azure/04AE50-SMT_queries_are.mp3", t_193));
        final long t_194 = t_193 + 4570L; // 1080863 (00:18:00:863)
        medias.add(new Sound("/audio/azure/133AB4-We_found_these_.mp3", t_194));
        final long t_195 = t_194 + 6658L; // 1087521 (00:18:07:521)
        medias.add(new Sound("/audio/azure/2D8378-For_less_capabl.mp3", t_195));
        final long t_196 = t_195 + 6392L; // 1093913 (00:18:13:913)
        medias.add(new Image("/image/14-hamr-abstraction-1.png", t_196)); // #60
        final long t_197 = t_196;
        medias.add(new Sound("/audio/azure/9DEAB8-So_let_s_start_.mp3", t_197));
        final long t_198 = t_197 + 7592L; // 1101505 (00:18:21:505)
        medias.add(new Image("/image/14-hamr-abstraction-2.png", t_198)); // #61
        final long t_199 = t_198;
        medias.add(new Sound("/audio/azure/809129-We_now_want_to_.mp3", t_199));
        final long t_200 = t_199 + 7042L; // 1108547 (00:18:28:547)
        medias.add(new Sound("/audio/azure/7EBE33-Recall_that_if_.mp3", t_200));
        final long t_201 = t_200 + 7930L; // 1116477 (00:18:36:477)
        medias.add(new Sound("/audio/azure/EADE64-Also__you_have_.mp3", t_201));
        final long t_202 = t_201 + 10160L; // 1126637 (00:18:46:637)
        medias.add(new Image("/image/14-hamr-abstraction-3.png", t_202)); // #62
        final long t_203 = t_202;
        medias.add(new Sound("/audio/azure/86E768-Moreover__we_ca.mp3", t_203));
        final long t_204 = t_203 + 8002L; // 1134639 (00:18:54:639)
        medias.add(new Sound("/audio/azure/7A54E0-However__the_st.mp3", t_204));
        final long t_205 = t_204 + 5564L; // 1140203 (00:19:00:203)
        medias.add(new Image("/image/14-hamr-abstraction-4.png", t_205)); // #63
        final long t_206 = t_205 + 800L; // 1141003 (00:19:01:003)
        medias.add(new Sound("/audio/azure/1C78D8-On_the_GUMBO_pr.mp3", t_206));
        final long t_207 = t_206 + 27248L; // 1168251 (00:19:28:251)
        medias.add(new Image("/image/15-temp-control-1.png", t_207)); // #64
        final long t_208 = t_207;
        medias.add(new Sound("/audio/azure/EFCA6F-Here_s_the_exam.mp3", t_208));
        final long t_209 = t_208 + 4522L; // 1172773 (00:19:32:773)
        medias.add(new Sound("/audio/azure/69E08F-We_have_a_tempe.mp3", t_209));
        final long t_210 = t_209 + 14864L; // 1187637 (00:19:47:637)
        medias.add(new Image("/image/15-temp-control-2.png", t_210)); // #65
        final long t_211 = t_210;
        medias.add(new Sound("/audio/azure/676EB8-Using_Hammer_co.mp3", t_211));
        final long t_212 = t_211 + 11408L; // 1199045 (00:19:59:045)
        medias.add(new Image("/image/15-temp-control-3.png", t_212)); // #66
        final long t_213 = t_212;
        medias.add(new Sound("/audio/azure/D72137-Using_the_GUMBO.mp3", t_213));
        final long t_214 = t_213 + 13520L; // 1212565 (00:20:12:565)
        medias.add(new Image("/image/16-gumbo-1.png", t_214)); // #67
        final long t_215 = t_214;
        medias.add(new Sound("/audio/azure/237074-Here_is_the_GUM.mp3", t_215));
        final long t_216 = t_215 + 6440L; // 1219005 (00:20:19:005)
        medias.add(new Image("/image/16-gumbo-2.png", t_216)); // #68
        final long t_217 = t_216;
        medias.add(new Sound("/audio/azure/F94F49-The_example_con.mp3", t_217));
        final long t_218 = t_217 + 7858L; // 1226863 (00:20:26:863)
        medias.add(new Sound("/audio/azure/988492-For_example__th.mp3", t_218));
        final long t_219 = t_218 + 7954L; // 1234817 (00:20:34:817)
        medias.add(new Sound("/audio/azure/A18946-In_addition_to_.mp3", t_219));
        final long t_220 = t_219 + 12776L; // 1247593 (00:20:47:593)
        medias.add(new Video("/video/17-demo-temp-control.mp4", t_220, true, 1.0, 0.0, 333.0));  // #69
        final long t_221 = t_220;
        medias.add(new Sound("/audio/azure/5A1943-So__what_you_ar.mp3", t_221));
        final long t_222 = t_221 + 7066L; // 1254659 (00:20:54:659)
        medias.add(new Sound("/audio/azure/DA2AAF-The_code_has_be.mp3", t_222));
        final long t_223 = t_222 + 4168L; // 1258827 (00:20:58:827)
        medias.add(new Video("/video/17-demo-temp-control.mp4", t_223, true, 1.0, 333.0, 3000.0));  // #70
        final long t_224 = t_223 + 5800L; // 1264627 (00:21:04:627)
        medias.add(new Sound("/audio/azure/10FD93-Logeeka_has_alr.mp3", t_224));
        final long t_225 = t_224 + 5744L; // 1270371 (00:21:10:371)
        medias.add(new Video("/video/17-demo-temp-control.mp4", t_225, true, 1.0, 6000.0, 10000.0));  // #71
        final long t_226 = t_225;
        medias.add(new Sound("/audio/azure/8557DD-If_we_introduce.mp3", t_226));
        final long t_227 = t_226 + 8960L; // 1279331 (00:21:19:331)
        medias.add(new Video("/video/17-demo-temp-control.mp4", t_227, true, 1.0, 10000.0, 14333.0));  // #72
        final long t_228 = t_227;
        medias.add(new Sound("/audio/azure/20C32A-A_problem_marke.mp3", t_228));
        final long t_229 = t_228 + 6536L; // 1285867 (00:21:25:867)
        medias.add(new Video("/video/17-demo-temp-control.mp4", t_229, true, 1.0, 14500.0, 0.0));  // #73
        final long t_230 = t_229;
        medias.add(new Sound("/audio/azure/DAD5D3-When_the_bug_is.mp3", t_230));
        final long t_231 = t_230 + 6800L; // 1292667 (00:21:32:667)
        medias.add(new Image("/image/18-logika-themes-parallel.png", t_231)); // #74
        final long t_232 = t_231;
        medias.add(new Sound("/audio/azure/DE6AE7-Let_s_now_consi.mp3", t_232));
        final long t_233 = t_232 + 5432L; // 1298099 (00:21:38:099)
        medias.add(new Image("/image/19-parallel-1.png", t_233)); // #75
        final long t_234 = t_233;
        medias.add(new Sound("/audio/azure/1CC617-One_key_observa.mp3", t_234));
        final long t_235 = t_234 + 10760L; // 1308859 (00:21:48:859)
        medias.add(new Image("/image/19-parallel-2.png", t_235)); // #76
        final long t_236 = t_235;
        medias.add(new Sound("/audio/azure/3D38B7-Moreover__Logee.mp3", t_236));
        final long t_237 = t_236 + 10448L; // 1319307 (00:21:59:307)
        medias.add(new Image("/image/19-parallel-3.png", t_237)); // #77
        final long t_238 = t_237;
        medias.add(new Sound("/audio/azure/87CE89-In_the_future__.mp3", t_238));
        final long t_239 = t_238 + 12322L; // 1331629 (00:22:11:629)
        medias.add(new Sound("/audio/azure/4B6208-In_such_setup__.mp3", t_239));
        final long t_240 = t_239 + 5482L; // 1337111 (00:22:17:111)
        medias.add(new Sound("/audio/azure/BFF8C5-We_believe_para.mp3", t_240));
        final long t_241 = t_240 + 8696L; // 1345807 (00:22:25:807)
        medias.add(new Image("/image/19-parallel-4.png", t_241)); // #78
        final long t_242 = t_241;
        medias.add(new Sound("/audio/azure/A9352F-It_is_especiall.mp3", t_242));
        final long t_243 = t_242 + 9128L; // 1354935 (00:22:34:935)
        medias.add(new Image("/image/19-parallel-5.png", t_243)); // #79
        final long t_244 = t_243;
        medias.add(new Sound("/audio/azure/61825A-Now__allow_me_t.mp3", t_244));
        final long t_245 = t_244 + 5096L; // 1360031 (00:22:40:031)
        medias.add(new Video("/video/20-demo-logika-legion.mp4", t_245, true, 1.0, 0.0, 500.0));  // #80
        final long t_246 = t_245 + 1800L; // 1361831 (00:22:41:831)
        medias.add(new Sound("/audio/azure/9C9E17-Here_is_an_i_pa.mp3", t_246));
        final long t_247 = t_246 + 5168L; // 1366999 (00:22:46:999)
        medias.add(new Video("/video/20-demo-logika-legion.mp4", t_247, true, 1.0, 0.0, 2000.0));  // #81
        final long t_248 = t_247;
        medias.add(new Sound("/audio/azure/A73082-The_browser_is_.mp3", t_248));
        final long t_249 = t_248 + 11290L; // 1378289 (00:22:58:289)
        medias.add(new Sound("/audio/azure/9DFFF5-That_is__the_he.mp3", t_249));
        final long t_250 = t_249 + 11888L; // 1390177 (00:23:10:177)
        medias.add(new Video("/video/20-demo-logika-legion.mp4", t_250, true, 1.0, 2000.0, 4000.0));  // #82
        final long t_251 = t_250;
        medias.add(new Sound("/audio/azure/1D2FD2-This_particular.mp3", t_251));
        final long t_252 = t_251 + 9826L; // 1400003 (00:23:20:003)
        medias.add(new Sound("/audio/azure/045722-On_the_right_ha.mp3", t_252));
        final long t_253 = t_252 + 6752L; // 1406755 (00:23:26:755)
        medias.add(new Video("/video/20-demo-logika-legion.mp4", t_253, true, 1.0, 9000.0, 36000.0));  // #83
        final long t_254 = t_253 + 1800L; // 1408555 (00:23:28:555)
        medias.add(new Sound("/audio/azure/90D7A1-As_can_be_obser.mp3", t_254));
        final long t_255 = t_254 + 4930L; // 1413485 (00:23:33:485)
        medias.add(new Sound("/audio/azure/867E2D-Next__I_will_op.mp3", t_255));
        final long t_256 = t_255 + 9196L; // 1422681 (00:23:42:681)
        medias.add(new Video("/video/20-demo-logika-legion.mp4", t_256, false, 1.0, 36000.0, 49000.0));  // #84
        final long t_257 = t_256 + 12501L; // 1435182 (00:23:55:182)
        medias.add(new Video("/video/20-demo-logika-legion.mp4", t_257, true, 1.0, 49000.0, 60000.0));  // #85
        final long t_258 = t_257 + 1300L; // 1436482 (00:23:56:482)
        medias.add(new Sound("/audio/azure/1827EC-As_can_be_obser.mp3", t_258));
        final long t_259 = t_258 + 8360L; // 1444842 (00:24:04:842)
        medias.add(new Image("/image/21-proof-engineering-1.png", t_259)); // #86
        final long t_260 = t_259;
        medias.add(new Sound("/audio/azure/B2995F-Finally__for_th.mp3", t_260));
        final long t_261 = t_260 + 2192L; // 1447034 (00:24:07:034)
        medias.add(new Image("/image/21-proof-engineering-2.png", t_261)); // #87
        final long t_262 = t_261 + 800L; // 1447834 (00:24:07:834)
        medias.add(new Sound("/audio/azure/535237-we_are_not_clai.mp3", t_262));
        final long t_263 = t_262 + 4954L; // 1452788 (00:24:12:788)
        medias.add(new Sound("/audio/azure/1C822C-However__in_pra.mp3", t_263));
        final long t_264 = t_263 + 8984L; // 1461772 (00:24:21:772)
        medias.add(new Video("/video/06-demo-logika.mp4", t_264, true, 2.0, 213000.0, 214000.0));  // #88
        final long t_265 = t_264;
        medias.add(new Sound("/audio/azure/E1D517-Here_we_see_how.mp3", t_265));
        final long t_266 = t_265 + 6826L; // 1468598 (00:24:28:598)
        medias.add(new Sound("/audio/azure/2C5BFD-Some_of_the_pro.mp3", t_266));
        final long t_267 = t_266 + 6728L; // 1475326 (00:24:35:326)
        medias.add(new Video("/video/06-demo-logika.mp4", t_267, true, 2.0, 221500.0, 234000.0));  // #89
        final long t_268 = t_267;
        medias.add(new Sound("/audio/azure/432D7B-Because_all_the.mp3", t_268));
        final long t_269 = t_268 + 8098L; // 1483424 (00:24:43:424)
        medias.add(new Sound("/audio/azure/1CA835-After_the_refac.mp3", t_269));
        final long t_270 = t_269 + 5530L; // 1488954 (00:24:48:954)
        medias.add(new Sound("/audio/azure/3D522F-Each_Slang_proo.mp3", t_270));
        final long t_271 = t_270 + 3596L; // 1492550 (00:24:52:550)
        medias.add(new Video("/video/06-demo-logika.mp4", t_271, true, 1.25, 245000.0, 256000.0));  // #90
        final long t_272 = t_271 + 800L; // 1493350 (00:24:53:350)
        medias.add(new Sound("/audio/azure/C90E14-The_numbering_d.mp3", t_272));
        final long t_273 = t_272 + 9464L; // 1502814 (00:25:02:814)
        medias.add(new Video("/video/06-demo-logika.mp4", t_273, true, 1.0, 261250.0, 272000.0));  // #91
        final long t_274 = t_273;
        medias.add(new Sound("/audio/azure/4F7C26-Each_proof_step.mp3", t_274));
        final long t_275 = t_274 + 9802L; // 1512616 (00:25:12:616)
        medias.add(new Sound("/audio/azure/AF579D-Logeeka_provide.mp3", t_275));
        final long t_276 = t_275 + 4484L; // 1517100 (00:25:17:100)
        medias.add(new Video("/video/06-demo-logika.mp4", t_276, true, 1.0, 273500.0, 278000.0));  // #92
        final long t_277 = t_276 + 800L; // 1517900 (00:25:17:900)
        medias.add(new Sound("/audio/azure/0A6DB4-The_premise_jus.mp3", t_277));
        final long t_278 = t_277 + 8530L; // 1526430 (00:25:26:430)
        medias.add(new Sound("/audio/azure/97B157-Custom_justific.mp3", t_278));
        final long t_279 = t_278 + 6634L; // 1533064 (00:25:33:064)
        medias.add(new Sound("/audio/azure/2FAC7C-Thus__to_keep_w.mp3", t_279));
        final long t_280 = t_279 + 18064L; // 1551128 (00:25:51:128)
        medias.add(new Image("/image/22-conclusion.png", t_280)); // #93
        final long t_281 = t_280 + 800L; // 1551928 (00:25:51:928)
        medias.add(new Sound("/audio/azure/103884-In_closing__in_.mp3", t_281));
        final long t_282 = t_281 + 10282L; // 1562210 (00:26:02:210)
        medias.add(new Sound("/audio/azure/45C475-All_of_these_to.mp3", t_282));
        final long t_283 = t_282 + 4210L; // 1566420 (00:26:06:420)
        medias.add(new Sound("/audio/azure/E4F99D-Logeeka_in_part.mp3", t_283));
        final long t_284 = t_283 + 11632L; // 1578052 (00:26:18:052)
        medias.add(new Image("/image/23-end.png", t_284)); // #94
        final long t_285 = t_284 + 800L; // 1578852 (00:26:18:852)
        medias.add(new Sound("/audio/azure/CD5E85-Thank_you_all_f.mp3", t_285));

        final long end = 1583180L; // 00:26:23:180

        if (width == -1 || height == -1) {
            final Rectangle2D rect = Screen.getPrimary().getBounds();
            width = rect.getWidth();
            height = rect.getHeight();
        }

        for (final Media media : medias) {
            final String uri = media.getUri();
            System.out.print("Loading " + uri + " ... ");
            System.out.flush();
            while (!media.isReady()) {
                if (media.hasError()) {
                    System.err.println("failed");
                    System.err.flush();
                    Platform.exit();
                }
                sleep(100);
            }
            System.out.println("done");
            System.out.flush();
        }
        final Thread thread = new Thread(() -> {
            while (Presentasi.this.stage == null) Presentasi.sleep(100);
            final int size = medias.size();
            long start = System.currentTimeMillis();
            int i = 0;
            if (slideNo > 0) {
                int j = 0;
                while (i < size && j < slideNo) {
                    if (!(medias.get(i) instanceof Sound)) {
                        j = j + 1;
                    }
                    i++;
                }
                while (i < size && medias.get(i) instanceof Sound) i++;
                if (i < size) start = start - medias.get(i).getTimeline();
            } else if (startTime > 0) {
                while (i < size && medias.get(i).getTimeline() < startTime) {
                    i++;
                }
                while (i < size && medias.get(i) instanceof Sound) i++;
                if (i < size) start = start - medias.get(i).getTimeline();
            }
            while (i < size) {
                final Media media = medias.get(i);
                while (System.currentTimeMillis() - start <= media.getTimeline()) Presentasi.sleep(TIMELINE_GRANULARITY);
                if (media instanceof Sound) {
                    final MediaPlayer mediaPlayer = ((Sound) media).mediaPlayer;
                    mediaPlayer.setVolume(TEXT_VOLUME);
                    mediaPlayer.play();
                } else if (media instanceof Image) {
                    final Image graphic = (Image) media;
                    final StackPane root = new StackPane();
                    final ImageView imageView = graphic.imageView;
                    root.getChildren().add(imageView);
                    imageView.setPreserveRatio(true);
                    imageView.setSmooth(true);
                    imageView.setFitWidth(width);
                    imageView.setFitHeight(height);
                    stage.getScene().setRoot(root);
                    Platform.runLater(() -> stage.show());
                } else if (media instanceof Video) {
                    final Video video = (Video) media;
                    final StackPane root = new StackPane();
                    final MediaView mediaView = video.mediaView;
                    root.getChildren().add(mediaView);
                    mediaView.setPreserveRatio(true);
                    mediaView.setSmooth(true);
                    mediaView.setFitWidth(width);
                    mediaView.setFitHeight(height);
                    final MediaPlayer player = mediaView.getMediaPlayer();
                    player.setStartTime(Duration.millis(video.startMillis));
                    player.setRate(video.rate);
                    if (video.endMillis > 0.0) player.setStopTime(Duration.millis(video.endMillis));
                    player.setVolume(1.0);
                    player.setMute(video.muted);
                    Platform.runLater(() -> {
                        player.play();
                        if (video.startMillis > 0) {
                            Presentasi.sleep(VSEEK_DELAY);
                        }
                        stage.getScene().setRoot(root);
                        stage.show();
                    });
                }
                i++;
            }
            while (System.currentTimeMillis() - start <= end) Presentasi.sleep(TIMELINE_GRANULARITY);
            Platform.exit();
        });
        thread.setDaemon(true);
        thread.start();
    }

    public static void sleep(final long millis) {
        try {
            Thread.sleep(millis);
        } catch (final Throwable t) {
            // skip
        }
    }

    @Override
    public void start(final Stage primaryStage) {
        primaryStage.setFullScreenExitHint("");
        primaryStage.setFullScreen(fullScreen);
        primaryStage.setResizable(!fullScreen);
        final Scene scene = new Scene(new StackPane(), width, height);
        primaryStage.setScene(scene);
        this.stage = primaryStage;
    }

}